module.exports = (sequelize, DataTypes) => sequelize.define("Payslip", {
    id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
    payment_batch_id: { type: DataTypes.UUID, allowNull: false },
    payroll_line_id: { type: DataTypes.UUID, allowNull: false },
    staff_id: { type: DataTypes.UUID, allowNull: false },
    payslip_reference: { type: DataTypes.STRING(60), allowNull: false, unique: true },
    company_name: { type: DataTypes.STRING(150), allowNull: false },
    employee_reference: { type: DataTypes.STRING(100), allowNull: false },
    employee_name: { type: DataTypes.STRING(150), allowNull: false },
    pay_period_start: { type: DataTypes.DATEONLY, allowNull: false },
    pay_period_end: { type: DataTypes.DATEONLY, allowNull: false },
    gross_pay: { type: DataTypes.DECIMAL(12,2), allowNull: false },
    incentive_pay: { type: DataTypes.DECIMAL(12,2), allowNull: false },
    cpf_amount: { type: DataTypes.DECIMAL(12,2), allowNull: false },
    sdl_amount: { type: DataTypes.DECIMAL(12,2), allowNull: false },
    other_deduction: { type: DataTypes.DECIMAL(12,2), allowNull: false, defaultValue: 0 },
    net_pay: { type: DataTypes.DECIMAL(12,2), allowNull: false },
    batch_reference: { type: DataTypes.STRING(50), allowNull: false },
    generated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
}, { tableName: "payslip", underscored: true, timestamps: true });
